######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 9 11:55:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += t002.cpp
