######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 14 12:27:27 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AddressBook.h
SOURCES += AddressBook.cpp main.cpp
