######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 9 13:46:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Notepad.h
SOURCES += main.cpp Notepad.cpp
