indentAfterHeadings:
    part:
        indent: 0
        level: 1
    chapter:
        indent: 1
        level: 2
    section:
        indent: 1
        level: 4
    subsection:
        indent: 1
        level: 6
    subsubsection:
        indent: 1
        level: 8
