######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 9 10:56:45 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += t001.cpp
