######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 17 17:04:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += t70_qdir_from_filepath.cpp
