######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 30 09:05:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += t69_qstring_arg.cpp
